# =================================================================
#
# Authors: Just van den Broecke <justb4@gmail.com>>
#          Jorge Samuel Mendes de Jesus <jorge.dejesus@geocat.net>
#          Tom Kraldis <tomkralidis@gmail.com>
#
# Copyright (c) 2019 Just van den Broecke
# Copyright (c) 2019 Jorge Samuel Mendes de Jesus
# Copyright (c) 2020 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000/
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: pygeoapi eMOTIONAL Cities instance
        description: Provides an API to eMOTIONAL Cities geospatial data
        keywords:
            - geospatial
            - data
            - api
            - eMOTIONAL Cities
            - Neuroscience
            - Urban Planning
            - H2020
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: ByteRoad
        url: https://byteroad.net
    contact:
        name: ByteRoad
        position: Maintainer
        address: R. Ricardo Espirito Santo
        city: Lisbon
        stateorprovince: Lisbon
        postalcode: 1200
        country: Portugal
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: info@byteroad.net
        url: https://byteroad.net
        hours: Hours of Service
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources:

    obs:
        type: collection
        title: Lisbon_20210912
        description: Environmental measurements in Lisbon - dry run.
        keywords:
            - Mesurements
            - Environmental
            - Lisbon
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-populated-places/
              hreflang: en-US
            - type: application/gzip
              rel: canonical
              title: download
              href: http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_populated_places_simple.zip
              hreflang: en-US
        extents:
            spatial:
                bbox: [-9.1353880000000007,38.7098030000000008,-9.1282750000000004,38.7172610000000006]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: Elasticsearch
              #Note elastic_search is the docker container of ES the name is defined in the docker-compose.yml
              data: http://elastic_search:9200/obs
              id_field: fid
            - type: tile
              name: MVT
              # data: http://minio:9000/obs/{z}/{x}/{y}
              data:  /pygeoapi/obs
              options:
              metadata_format: tilejson
              bounds: [[-180.0,-90.0],[180.0,90.0]]
              zoom:
                    min: 0
                    max: 11
              schemes:
                    #- WebMercatorQuad
                    - WorldCRS84Quad
              format: 
                    name: pbf
                    mimetype: application/vnd.mapbox-vector-tile
    obs_rec:
        type: collection
        title: Lisbon_20210912_pr
        description: Environmental measurements in Lisbon - dry run.
        keywords:
            - Mesurements
            - Environmental
            - Lisbon
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-populated-places/
              hreflang: en-US
            - type: application/gzip
              rel: canonical
              title: download
              href: http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_populated_places_simple.zip
              hreflang: en-US
        extents:
            spatial:
                bbox: [-9.1353880000000007,38.7098030000000008,-9.1282750000000004,38.7172610000000006]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: record
              name: Elasticsearch
              #Note elastic_search is the docker container of ES the name is defined in the docker-compose.yml
              data: http://elastic_search:9200/obs
              id_field: fid
              time_field: datetime

